### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 807502278** [chaojie/ComfyUI-MuseTalk#1]
Traceback (most recent call last):
  File "D:\AI\ComfyUI-aki-v1_new\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI-aki-v1_new\custom_nodes\ComfyUI-MuseTalk\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "D:\AI\ComfyUI-aki-v1_new\custom_nodes\ComfyUI-MuseTalk\nodes.py", line 25, in <module>
    from musetalk.utils.utils import get_file_type,get_video_fps,datagen
  File "D:\AI\ComfyUI-aki-v1_new/custom_nodes/ComfyUI-MuseTalk\musetalk\utils\utils.py", line 23, in <module>
    from musetalk.models.vae import VAE
ModuleNotFoundError: No module named 'musetalk.models'

**Comment by 807502278** [comment]
Desktop> D:\AI\ComfyUI-aki-v1_new\python\python.exe -m pip show openmim mmengine mmcv mmdet mmpose
Name: openmim
Version: 0.3.9
Summary: MIM Installs OpenMMLab packages
Home-page: https://github.com/open-mmlab/mim
Author: MIM Authors
Author-email: openmmlab@gmail.com
License:
Location: d:\ai\comfyui-aki-v1_new\python\lib\site-packages
Requires: Click, colorama, model-index, opendatalab, pandas, pip, requests, rich, tabulate
Required-by:
---
Name: mmengine
Version: 0.10.3
Summary: Engine of OpenMMLab projects
Home-page: https://github.com/open-mmlab/mmengine
Author: MMEngine Authors
Author-email: openmmlab@gmail.com
License: UNKNOWN
Location: d:\ai\comfyui-aki-v1_new\python\lib\site-packages
Requires: addict, matplotlib, numpy, opencv-python, pyyaml, regex, rich, termcolor, yapf
Required-by: mmcv
---
Name: mmcv
Version: 2.1.0
Summary: OpenMMLab Computer Vision Foundation
Home-page: https://github.com/open-mmlab/mmcv
Author: MMCV Contributors
Author-email: openmmlab@gmail.com
License:
Location: d:\ai\comfyui-aki-v1_new\python\lib\site-packages
Requires: addict, mmengine, numpy, opencv-python, packaging, Pillow, pyyaml, regex, yapf
Required-by:
---
Name: mmdet
Version: 3.1.0
Summary: OpenMMLab Detection Toolbox and Benchmark
Home-page: https://github.com/open-mmlab/mmdetection
Author: MMDetection Contributors
Author-email: openmmlab@gmail.com
License: Apache License 2.0
Location: d:\ai\comfyui-aki-v1_new\python\lib\site-packages
Requires: matplotlib, numpy, pycocotools, scipy, shapely, six, terminaltables
Required-by:
---
Name: mmpose
Version: 1.3.1
Summary: OpenMMLab Pose Estimation Toolbox and Benchmark.
Home-page: https://github.com/open-mmlab/mmpose
Author: MMPose Contributors
Author-email: openmmlab@gmail.com
License: Apache License 2.0
Location: d:\ai\comfyui-aki-v1_new\python\lib\site-packages
Requires: chumpy, json-tricks, matplotlib, munkres, numpy, opencv-python, pillow, scipy, torchvision, xtcocotools
Required-by:

**Comment by LeoMusk** [comment]
same+1

**Comment by 807502278** [comment]
I'll try Python 3.10.11+torch 2.1.2+cu118

**Comment by bluetyhyhf** [comment]
I'm getting the exact same error. Python 3.11+torch 2.2.0+cu121
