### ISSUE TITLE
启动comfyui后会直接加载模型, 而不是执行时再加载, 占用7G显存, 有类似情况吗

### ISSUE THREAD

**Issue by luoguohui99** [chaojie/ComfyUI-MuseTalk#10]

**Comment by jnc-nj** [comment]
加载模型的函数放在最外层了，导致启动就会一直加载；还是先用单独的webui来搞吧

**Comment by cjl84914** [comment]
我也遇到这种情况

**Comment by Pythonpa** [comment]
是的有这个问题。需要修改下，不然直接一启动就占用了你几个G的显存

**Comment by DeepAichemist** [comment]
兄弟，你现在解决这个问题了吗

**Comment by luoguohui99** [comment]
nodes.py第34行的模型加载audio_processor,vae,unet,pe  = load_all_model()放到MuseTalkRun的run函数里面可以解决这个问题
