### ISSUE TITLE
【help】You should install ``mmcv`` rather than ``mmcv-lite`

### ISSUE THREAD

**Issue by gtbloody** [chaojie/ComfyUI-MuseTalk#24]
![image](https://github.com/chaojie/ComfyUI-MuseTalk/assets/130019359/dab5bced-460e-4368-86ae-65a398e340dc)
i've already installed mmcv,mmdet and mmpose,but when I run comfyui,logs says '  You should install ``mmcv`` rather than ``mmcv-lite`` if you need this module.'
if I install mmcv-full,logs changes to"no module called 'mmcv',"
我已经用mim install安装了三个mm依赖，可是启动comfyui时提醒我不应该装mmcv-lite,我装的是mmcv 2.1.0，mmdet3.2.0和mmpose1.3.1。怎么回事呢? 而且这三个依赖版本我在单独部署的museV上是验证通过的，但那个环境我用conda装的，这个comfyui用的秋叶的启动器的环境。
QAQ

**Comment by wfjsw** [comment]
Please use 
```
python -m pip
``` 
in replacement of any `pip` call, and use
```
python -m mim
```
in replacement of any `mim` call. 

> https://github.com/comfyanonymous/ComfyUI/discussions/2635 
> 
> It is important to know that the only [officially](https://github.com/pypa/pip/issues/3164) [supported](https://pip.pypa.io/en/stable/user_guide/#running-pip) [way](https://github.com/pypa/pip/issues/7498) to invoke pip is through `python -m pip`. It is neither `pip` nor `import pip`. The `pip` or `pip.exe` could simply not be there and you risk installing some packages into a different environment rather than that you are running on.

**Comment by gtbloody** [comment]
> Please use
> 
> ```
> python -m pip
> ```
> 
> in replacement of any `pip` call, and use
> 
> ```
> python -m mim
> ```
> 
> in replacement of any `mim` call.
> 
> > [comfyanonymous/ComfyUI#2635](https://github.com/comfyanonymous/ComfyUI/discussions/2635)
> > It is important to know that the only [officially](https://github.com/pypa/pip/issues/3164) [supported](https://pip.pypa.io/en/stable/user_guide/#running-pip) [way](https://github.com/pypa/pip/issues/7498) to invoke pip is through `python -m pip`. It is neither `pip` nor `import pip`. The `pip` or `pip.exe` could simply not be there and you risk installing some packages into a different environment rather than that you are running on.
----------------------------------------------
谢谢大佬在群里的回复。
mmdet 3.3.0和mmpose1.3.1都要求mmcv<2.2.0，mmcv版本又和torch版本挂钩，一环扣一环
我查了官方文档，mmcv2.1.0只能把torch降到2.1.x才行
https://mmcv.readthedocs.io/en/latest/get_started/installation.html
